"""Render research/report.md from per-cohort result JSONs.

Verdicts come straight from the frozen criteria in run_study.py (which
implement protocol.md §3). This renderer formats; it never re-judges.
"""

import json
from pathlib import Path

RESEARCH = Path(__file__).resolve().parent
RESULTS = RESEARCH / "results"
OUT = RESEARCH / "report.md"

COHORT_ORDER = ["C50", "C40", "C36", "C20", "C10"]
HYPOTHESES = ["H1a", "H1b", "H2", "H3", "H4", "H5", "H5b", "H6", "H7", "H8"]


def _load() -> dict:
    out = {}
    for c in COHORT_ORDER:
        p = RESULTS / f"{c}.json"
        if p.exists():
            out[c] = json.loads(p.read_text())
    return out


def _verdict_of(block) -> str:
    """Extract a single verdict string from a hypothesis block that may be
    a dict of sub-results (worst verdict wins, 分歧 > 大體一致 > 支持)."""
    order = {"支持": 0, "大體一致": 1, "分歧": 2}
    if block is None:
        return "n/a"
    if isinstance(block, dict):
        if "verdict" in block:
            return str(block["verdict"])
        verdicts = [
            str(v.get("verdict"))
            for v in block.values()
            if isinstance(v, dict) and "verdict" in v
        ]
        verdicts = [
            v
            for v in verdicts
            if v in order or v.startswith("大體一致") or v.startswith("分歧")
        ]
        if not verdicts:
            return "n/a"

        def rank(v):
            for key, r in order.items():
                if v.startswith(key):
                    return r
            return 1

        return max(verdicts, key=rank)
    return "n/a"


def render() -> str:
    data = _load()
    lines = [
        "# PRISM Historical Validation Study — Report",
        "",
        "Generated by `research/run_study.py` + `render_report.py`. "
        "Protocol frozen at tag `study-preregistered` "
        "(PRISM under test: `cd565a96`). Verdict semantics: "
        "支持 = all pre-registered criteria met; 大體一致 = direction/sign "
        "correct but a calibration or stability sub-test failed; "
        "分歧 = criterion missed or sign contradicts ground truth.",
        "",
        "## Verdict matrix",
        "",
    ]
    header = "| Hypothesis | " + " | ".join(data.keys()) + " |"
    sep = "|---" * (len(data) + 1) + "|"
    lines += [header, sep]
    for h in HYPOTHESES:
        row = [h]
        for c in data:
            row.append(_verdict_of(data[c].get(h)))
        lines.append("| " + " | ".join(row) + " |")
    lines.append("")

    for c, res in data.items():
        lines += [f"## {c} — {res['window'][0]} → {res['window'][1]}", ""]
        lines.append(
            f"Audit: {res['audit']['rows']} rows / "
            f"{res['audit']['expected_bdays']} expected bdays "
            f"({res['audit']['fraction']*100:.1f}%) — "
            f"{'PASS' if res['audit']['passed'] else 'ABORT'}; "
            f"runtime {res.get('runtime_s','?')}s"
        )
        lines.append("")
        for h in HYPOTHESES:
            if h not in res:
                continue
            lines.append(f"### {h}")
            lines.append("```json")
            lines.append(json.dumps(res[h], indent=2, ensure_ascii=False, default=str))
            lines.append("```")
            lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    OUT.write_text(render())
    print(f"wrote {OUT}")
