/**
 * The chart recognizers, run against real tool payloads.
 *
 *   node --test tests/unit/chartSpec.test.ts
 *
 * `tests/fixtures/tool_payloads.json` is not hand-written: it is the actual
 * output of the gateway tool functions, generated by importing the Lambda
 * handlers and calling them with the arguments the starter questions cause the
 * agent to use (/tmp/capture_payloads.py). That matters because the recognizers index into specific key
 * names (`weekly_data[].units_sold`, `trends[].median_sale_price`), and a test
 * built on invented payloads would pass while the real shapes drifted underneath.
 * The arguments matter as much as the shapes: a six-drug interaction check
 * captured a payload with a non-zero severity summary and its recognizer passed,
 * while the live app — which asks about three drugs — showed no panel at all.
 *
 * The assertions that carry the most weight are the negative ones. This feature
 * shows a chart next to an agent's answer, so a *wrong* chart is worse than no
 * chart — the numbers on screen would contradict the numbers in the reply. So
 * every recognizer must return null rather than half-draw when the payload does
 * not match, and unrecognized tools must produce nothing at all.
 *
 * Mutation-checked; see the bottom of this file for what was verified.
 */
import { test } from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { chartFor, CHARTABLE_TOOLS } from '../../web/src/lib/chartSpec.ts'

const payloads = JSON.parse(
  readFileSync(new URL('../fixtures/tool_payloads.json', import.meta.url), 'utf8'),
) as Record<string, unknown>

/** Guard against a vacuous suite: an empty fixture would satisfy every loop. */
test('the fixture holds real payloads for every chartable tool', () => {
  assert.ok(
    Object.keys(payloads).length >= 53,
    `fixture has ${Object.keys(payloads).length} payloads; expected the full capture`,
  )
  for (const tool of CHARTABLE_TOOLS) {
    assert.ok(payloads[tool], `no captured payload for ${tool} — its test would be vacuous`)
  }
})

test('every chartable tool produces a chart from its real payload', () => {
  for (const tool of CHARTABLE_TOOLS) {
    const spec = chartFor(tool, payloads[tool])
    assert.ok(spec, `${tool}: recognizer returned null for its own real payload`)
    assert.ok(spec.title.trim(), `${tool}: empty title`)
    assert.ok(spec.data.length >= 2, `${tool}: ${spec.data.length} rows — not a chart`)
    assert.ok(spec.series.length >= 1, `${tool}: no series`)
  }
})

test('every series key resolves to a finite number in every row', () => {
  // The failure this prevents is a chart that renders as a flat line or an empty
  // grid: recharts silently draws nothing for a key that is missing or a string,
  // so a typo'd key produces an axis with no data rather than an error.
  for (const tool of CHARTABLE_TOOLS) {
    const spec = chartFor(tool, payloads[tool])!
    for (const series of spec.series) {
      for (const [i, row] of spec.data.entries()) {
        const value = row[series.key]
        assert.equal(
          typeof value,
          'number',
          `${tool}: row ${i} key "${series.key}" is ${typeof value}, not a number`,
        )
        assert.ok(
          Number.isFinite(value as number),
          `${tool}: row ${i} key "${series.key}" is not finite`,
        )
      }
    }
    for (const [i, row] of spec.data.entries()) {
      const x = row[spec.xKey]
      assert.ok(
        typeof x === 'string' || typeof x === 'number',
        `${tool}: row ${i} has no x value at "${spec.xKey}"`,
      )
    }
  }
})

test('charted values match the payload rather than being recomputed', () => {
  // Spot-check the two shapes with the most transformation between payload and
  // chart. If a recognizer ever starts deriving values, the panel would show
  // numbers the agent's reply does not contain — the exact defect this whole
  // feature exists to avoid.
  const sectors = chartFor('get_sector_performance', payloads.get_sector_performance)!
  const raw = (payloads.get_sector_performance as { sectors: Array<Record<string, unknown>> })
    .sectors
  const tech = raw.find((s) => s.name === 'Technology')!
  const charted = sectors.data.find((row) => row.sector === 'Technology')!
  assert.equal(charted.daily, tech.daily_change_pct)

  const bp = chartFor('get_patient_analytics', payloads.get_patient_analytics)!
  const bpRaw = (
    payloads.get_patient_analytics as {
      trends: { blood_pressure: { data: Array<Record<string, unknown>> } }
    }
  ).trends.blood_pressure.data
  assert.equal(bp.data.length, bpRaw.length)
  assert.equal(bp.data[0].systolic, bpRaw[0].systolic)
  assert.equal(bp.data[0].diastolic, bpRaw[0].diastolic)
})

test('ranked charts are sorted so the extremes read off the ends', () => {
  // "Which sectors are leading and lagging" is a literal starter question; an
  // unsorted bar chart answers it worse than the table did.
  const sectors = chartFor('get_sector_performance', payloads.get_sector_performance)!
  const values = sectors.data.map((row) => Number(row.daily))
  assert.deepEqual(values, [...values].sort((a, b) => b - a))

  // Health scores sort the other way: the asset needing attention goes first.
  const fleet = chartFor('get_equipment_list', payloads.get_equipment_list)!
  const health = fleet.data.map((row) => Number(row.health))
  assert.deepEqual(health, [...health].sort((a, b) => a - b))
})

test('an unrecognized tool produces no chart', () => {
  // The panel must stay hidden for the many tools with nothing to plot, rather
  // than inventing an axis out of whatever numbers a payload happens to hold.
  for (const tool of ['skills', 'search_knowledge_base', 'place_order', 'schedule_appointment']) {
    assert.equal(chartFor(tool, { anything: [1, 2, 3] }), null, `${tool} should not chart`)
  }
})

test('a recognized tool with the wrong payload shape produces no chart', () => {
  // Tool output changing shape must degrade to "no panel", never to a broken axis.
  for (const tool of CHARTABLE_TOOLS) {
    for (const junk of [null, undefined, {}, [], 'text', 42, { sectors: [] }, { data: {} }]) {
      assert.equal(
        chartFor(tool, junk),
        null,
        `${tool}: charted junk payload ${JSON.stringify(junk)}`,
      )
    }
  }
})

test('a tool error payload produces no chart', () => {
  // tool_error() returns {"error": "..."} with HTTP success, so this arrives as a
  // successful tool result and would otherwise reach the recognizers.
  assert.equal(
    chartFor('get_sector_performance', { error: 'Portfolio not found: default' }),
    null,
  )
  assert.equal(chartFor('get_market_overview', { error: 'boom', indices: {} }), null)
})

test('a single-row payload produces no chart', () => {
  // One bar is a number with extra ink. The threshold is where the panel stops
  // being an improvement over the sentence in the reply.
  assert.equal(
    chartFor('get_demand_trends', { weekly_data: [{ week: '2026-W28', units_sold: 100 }] }),
    null,
  )
})

test('non-numeric values are dropped rather than coerced to zero', () => {
  // A null reading plotted as 0 would put a spike to the baseline on a vibration
  // chart, which reads as an equipment fault that did not happen.
  const spec = chartFor('get_sensor_data', {
    sensor_type: 'vibration',
    equipment_id: 'EQ-CNC-001',
    unit: 'mm/s',
    readings: [
      { timestamp: '2026-08-05T01:00:00Z', value: 3.1 },
      { timestamp: '2026-08-05T02:00:00Z', value: null },
      { timestamp: '2026-08-05T03:00:00Z', value: 3.4 },
    ],
    thresholds: { warning: 5, critical: 8 },
  })!
  assert.equal(spec.data.length, 2, 'the null reading should be dropped, not zeroed')
  assert.deepEqual(
    spec.data.map((row) => row.value),
    [3.1, 3.4],
  )
})

test('sensor thresholds become dashed reference lines, not series', () => {
  // Status thresholds as a data series would read as a measurement.
  const spec = chartFor('get_sensor_data', payloads.get_sensor_data)!
  assert.equal(spec.series.length, 1)
  assert.ok(spec.refLines && spec.refLines.length >= 1, 'thresholds should be reference lines')
  const thresholds = (payloads.get_sensor_data as { thresholds: Record<string, number> })
    .thresholds
  // The warning limit is what makes the reading mean something: 3.7 mm/s is only
  // reassuring once you can see the 7.1 line it sits under. This is the one chart
  // whose threshold is worth widening the axis for.
  assert.ok(
    spec.refLines!.some((line) => line.y === thresholds.warning),
    'the nearest threshold is the answer to "is this a problem" and must be drawn',
  )
  // And unconditionally — the readings are synthetic and re-seeded daily, so on a
  // quiet day the series sits low enough that the warning line fails the
  // MIN_DATA_SHARE gate. Gating it shipped a chart with no line at all while the
  // reply discussed ISO zones the reader could not see: a healthy margin is not
  // distortion, it is the picture. Pinned with a fixture-independent quiet day.
  const quiet = {
    ...(payloads.get_sensor_data as Record<string, unknown>),
    readings: [
      { timestamp: '2026-08-04T11:30:00+00:00', value: 1.25 },
      { timestamp: '2026-08-04T11:45:00+00:00', value: 2.1 },
      { timestamp: '2026-08-04T12:00:00+00:00', value: 3.07 },
    ],
  }
  const calm = chartFor('get_sensor_data', quiet)!
  assert.ok(
    calm.refLines!.some((line) => line.y === thresholds.warning),
    'a quiet series still needs its warning line — the margin is the information',
  )
  // The critical limit is not: at 11.0 against a 4.5 peak it more than doubles the
  // axis, flattening the trend — the other half of the answer — into the bottom
  // sixth of the plot, to show a line the warning line has already answered. It
  // earns its place only when the reading is actually climbing towards it.
  assert.ok(
    !spec.refLines!.some((line) => line.y === thresholds.critical),
    'a far-off critical limit must not flatten the series it is meant to qualify',
  )
  const climbing = {
    ...(payloads.get_sensor_data as Record<string, unknown>),
    readings: [
      { timestamp: '2026-08-04T11:30:00+00:00', value: 6.4 },
      { timestamp: '2026-08-04T11:45:00+00:00', value: 7.9 },
      { timestamp: '2026-08-04T12:00:00+00:00', value: 8.8 },
    ],
  }
  const urgent = chartFor('get_sensor_data', climbing)!
  assert.ok(
    urgent.refLines!.some((line) => line.y === thresholds.critical),
    'an asset approaching Zone D must show the Zone D line',
  )
})

test('a network-wide threshold is not drawn against per-location bars', () => {
  // This one is not about geometry — it comfortably passes the axis-share test
  // below, at 36%. It is about what the two numbers count. reorder_point (1498)
  // and safety_stock (749) are stated for the whole network, against a
  // total_on_hand of 2375 that is the sum of these six locations; the largest
  // single location holds 539. Drawn on this axis the line clears every bar and
  // says "every location is critically short" while the same payload's
  // needs_reorder is false. Labelling it "network reorder pt" was the first
  // attempt and it is not enough: a caption cannot undo a wrong denominator, and
  // the per-location thresholds that would belong here are not in the payload.
  const spec = chartFor('check_inventory', payloads.check_inventory)!
  const metrics = (
    payloads.check_inventory as {
      metrics: { reorder_point: number; safety_stock: number; needs_reorder: boolean }
      inventory: { total_on_hand: number }
      by_location: Record<string, number>
    }
  )
  const biggest = Math.max(...Object.values(metrics.by_location))
  // Pins the premise: these are network figures, so they dwarf any one location.
  assert.ok(
    metrics.metrics.reorder_point > biggest,
    'fixture no longer exercises the network-vs-location mismatch',
  )
  assert.equal(
    metrics.inventory.total_on_hand,
    Object.values(metrics.by_location).reduce((a, b) => a + b, 0),
  )
  assert.equal(metrics.metrics.needs_reorder, false)
  assert.deepEqual(
    spec.refLines ?? [],
    [],
    'a network threshold on per-location bars contradicts the payload it came from',
  )
})

test('no reference line is drawn so far off that it distorts its own chart', () => {
  // recharts defaults ReferenceLine to ifOverflow="discard": a line outside the
  // axis domain vanishes with no warning, which is how the vibration chart shipped
  // with neither of its ISO 10816 lines. The component now sets
  // ifOverflow="extendDomain" so a line is never silently dropped — which moves
  // the failure from "invisible" to "the series is squashed to make room", and
  // that is the failure this test exists to keep out.
  //
  // The bound is geometric, not a distance: what a reader loses is the share of the
  // plot the data occupies once the axis has been stretched to fit the line. So
  // that share is what is measured. A bar axis is anchored at 0 (type="number"
  // with no domain), a line axis at the data (domain={['auto','auto']}).
  //
  // A third is the floor. At 42% (3.7 mm/s readings under a 7.1 warning line) the
  // trend is still readable and the line is worth it; at 22% (the same readings
  // under an 11.0 critical line) and 29% (a 224h capacity line over a 66h week) it
  // is not.
  //
  // One deliberate exception: a sensor chart's NEAREST limit is exempt, because
  // there the gap between series and line is not distortion but the answer itself
  // (a healthy margin). Everything past the first line pays full price. The
  // exemption is scoped to the first line so this test still catches a recognizer
  // that stacks a far-off second threshold behind an exempt first one.
  const MIN_DATA_SHARE = 1 / 3
  const NEAREST_LINE_EXEMPT = new Set(['get_sensor_data'])
  for (const [key, payload] of Object.entries(payloads)) {
    const tool = key.split('__')[0]
    const spec = chartFor(tool, payload)
    if (!spec?.refLines?.length) continue
    const exemptFirst = NEAREST_LINE_EXEMPT.has(tool)
    const judged = exemptFirst ? spec.refLines.slice(1) : spec.refLines
    if (!judged.length) continue
    const values = spec.data
      .flatMap((row) => spec.series.map((s) => Number(row[s.key])))
      .filter((v) => Number.isFinite(v))
    const lo = spec.kind === 'bars' ? Math.min(0, ...values) : Math.min(...values)
    const hi = spec.kind === 'bars' ? Math.max(0, ...values) : Math.max(...values)
    const lines = spec.refLines.map((l) => l.y)
    // Every line is on the same axis, so they distort it together.
    const axis = Math.max(hi, ...lines) - Math.min(lo, ...lines)
    const share = axis === 0 ? 1 : (hi - lo) / axis
    assert.ok(
      share >= MIN_DATA_SHARE,
      `${key} · "${spec.title}": reference lines ${JSON.stringify(lines)} stretch the axis ` +
        `until the data [${lo}, ${hi}] occupies only ${(share * 100).toFixed(0)}% of it`,
    )
  }
})

test('percentage strings in HEDIS measures are parsed, not dropped', () => {
  // These arrive as "81%", the one place a payload reports a number as a string.
  const spec = chartFor('get_population_health_metrics', payloads.get_population_health_metrics)!
  const measures = (
    payloads.get_population_health_metrics as {
      quality_measures_hedis: Record<string, { performance: string }>
    }
  ).quality_measures_hedis
  assert.equal(spec.data.length, Object.keys(measures).length)
  const first = Object.values(measures)[0]
  assert.equal(spec.data[0].performance, Number.parseFloat(first.performance))
})

test('every starter question that calls a tool can produce a chart', () => {
  // This is the assertion the feature is actually judged on. The E2E census
  // (tests/e2e/starter-charts-audit.spec.ts) found that 14 of 26 starter
  // questions produced no panel, and in every case the answer had called only
  // tools with no recognizer. These are the tool names that census observed,
  // per question, so a recognizer being dropped shows up here rather than in a
  // 15-minute browser run against the live app.
  const observed: Record<string, string[]> = {
    'finance · Review my portfolio': ['get_portfolio_positions', 'get_portfolio_allocation'],
    'finance · Downside risk': ['calculate_var', 'stress_test_portfolio'],
    'healthcare · Care gaps': ['get_care_gap_analysis'],
    'healthcare · Readmission risk': ['get_readmission_risk', 'get_care_gap_analysis'],
    'healthcare · Check interactions': ['check_drug_interactions'],
    "healthcare · Dr. Chen's openings": ['get_provider_availability'],
    'insurance · Verify coverage': ['check_coverage'],
    'retail · Price the jacket': ['optimize_pricing', 'get_pricing_analysis'],
    'retail · Supplier health': ['get_supplier_performance'],
    'manufacturing · Will the turbine fail': ['predict_failure'],
    'manufacturing · Vibration on CNC-001': ['analyze_vibration'],
    'real-estate · Market conditions': ['get_market_conditions'],
    'real-estate · Value a property': ['generate_cma_report'],
    'real-estate · Find 3-bed homes': ['search_properties', 'get_market_conditions'],
  }
  for (const [question, tools] of Object.entries(observed)) {
    const charted = tools.filter((tool) => {
      const payload = payloads[tool]
      assert.ok(payload, `${tool}: no fixture payload, so this check is vacuous`)
      return chartFor(tool, payload) !== null
    })
    assert.ok(
      charted.length > 0,
      `${question}: none of ${tools.join(', ')} produces a chart — this question would show no panel`,
    )
  }
})

test('an all-zero severity summary shows no chart rather than empty bars', () => {
  // "No interactions found" is the good news, and it arrives as three zero
  // counts. Bars of height zero under the title "Interactions by severity" read
  // as a chart that failed to load, so the reply should say it in words instead.
  const clean = chartFor('check_drug_interactions', {
    medications_checked: ['metformin', 'atorvastatin'],
    pairs_analyzed: 1,
    interactions_found: 0,
    interactions: [],
    severity_summary: { major: 0, moderate: 0, minor: 0 },
    overall_risk: 'LOW - No significant interactions detected in the reference database.',
  })
  assert.equal(clean, null)

  // A real flagged pair does chart. Both fixtures are live captures: the starter
  // question's own three drugs, and a major-severity pair.
  for (const key of ['check_drug_interactions', 'check_drug_interactions__interacting']) {
    const payload = payloads[key] as { interactions_found: number }
    assert.ok(payload, `no fixture for ${key}`)
    assert.ok(payload.interactions_found > 0, `${key} captured no interaction`)
    const spec = chartFor('check_drug_interactions', payload)
    assert.ok(spec, `${key}: a flagged interaction should chart`)
    assert.ok(spec.data.some((row) => Number(row.count) > 0))
  }
})

test('reference lines carry thresholds the payload states, never derived targets', () => {
  // A dashed line is read as an authority ("the limit", "the median"). Inventing
  // one would put a threshold on screen that appears nowhere in the reply.
  const search = chartFor('search_properties', payloads.search_properties)!
  const median = (payloads.search_properties as { market_median_price: number })
    .market_median_price
  assert.ok(
    search.refLines?.some((line) => line.y === median),
    'listing prices should be drawn against the market median from the payload',
  )

  const conditions = chartFor('get_market_conditions', payloads.get_market_conditions)!
  const allTypes = (
    payloads.get_market_conditions as { market_snapshot: { median_sale_price: number } }
  ).market_snapshot.median_sale_price
  assert.ok(
    conditions.refLines?.some((line) => line.y === allTypes),
    'per-type medians only read as above/below market with the all-types median drawn',
  )

  const cma = chartFor('generate_cma_report', payloads.generate_cma_report)!
  const reconciled = (
    payloads.generate_cma_report as { value_conclusion: { reconciled_value: number } }
  ).value_conclusion.reconciled_value
  assert.ok(cma.refLines?.some((line) => line.y === reconciled))

  // The maintenance line is the one legitimate derivation, and it is stated:
  // period-wide technician hours divided down to a week. Plotted raw it would
  // sit above every bar and read as "nothing is near capacity".
  const cal = chartFor('get_maintenance_calendar', payloads.get_maintenance_calendar)!
  const util = (
    payloads.get_maintenance_calendar as {
      resource_utilization: { technician_hours_available: number }
      period_days: number
      weekly_capacity: Record<string, { maintenance_hours: number }>
    }
  )
  const weekly = Math.round(
    (util.resource_utilization.technician_hours_available / util.period_days) * 7,
  )
  assert.ok(
    !cal.refLines?.some(
      (line) => line.y === util.resource_utilization.technician_hours_available,
    ),
    'the period total must not be drawn as if it were a weekly capacity',
  )
  // Dividing by the period was necessary but not sufficient. This fleet's 960h
  // over 30 days is 224h/week against a busiest week of 65.9h, so even the
  // correctly-derived line is 3.4x off the top of the chart: drawn, it turns four
  // fifths of the plot into whitespace and every bar into a stub. The utilisation
  // percentage in the subtitle says "24%" in one word, so nothing is lost.
  const busiest = Math.max(
    ...Object.values(util.weekly_capacity).map((w) => w.maintenance_hours),
  )
  assert.ok(weekly > busiest * 1.25, 'fixture no longer exercises the far-off-line path')
  assert.deepEqual(cal.refLines ?? [], [], 'a line 3x above every bar must be withheld')

  // But it is withheld for being far away, not dropped outright: a fleet running
  // near capacity is exactly when the line matters most, and that must still work.
  const busy = {
    ...(payloads.get_maintenance_calendar as Record<string, unknown>),
    resource_utilization: {
      ...util.resource_utilization,
      technician_hours_available: 240,
    },
  }
  const busyWeekly = Math.round((240 / util.period_days) * 7)
  const busySpec = chartFor('get_maintenance_calendar', busy)!
  assert.ok(
    busySpec.refLines?.some((line) => line.y === busyWeekly),
    'a weekly capacity within reach of the bars is the case the line is for',
  )
})

test('scales that cannot share an axis are not plotted together', () => {
  // The supplier scorecard mixes 0-100 scores with defect_rate_ppm (thousands)
  // and lead times (single digits). One PPM bar would flatten every percentage
  // to invisibility, so the recognizer keeps only the comparable metrics.
  const spec = chartFor('get_supplier_performance', payloads.get_supplier_performance)!
  const metrics = (payloads.get_supplier_performance as { metrics: Record<string, number> })
    .metrics
  assert.ok(metrics.defect_rate_ppm > 100, 'fixture no longer has an out-of-scale metric')
  for (const row of spec.data) {
    const value = Number(row.value)
    assert.ok(value >= 0 && value <= 100, `${row.metric} at ${value} is off the 0-100 scale`)
  }
  assert.ok(!spec.data.some((row) => /ppm/i.test(String(row.metric))))
})

test('lab values are normalized against their own reference range', () => {
  // WBC in x10^3/uL and cholesterol in mg/dL share no axis. Plotting the raw
  // values would rank the tests by unit magnitude rather than by abnormality.
  const spec = chartFor('get_lab_results', payloads.get_lab_results)!
  const first = (
    payloads.get_lab_results as {
      results: Array<{ tests: Array<{ test: string; value: number; ref_range: string }> }>
    }
  ).results[0].tests[0]
  const upper = Number.parseFloat(first.ref_range.split('-')[1])
  const charted = spec.data.find((row) => row.test === first.test)!
  assert.equal(charted.pctOfLimit, Math.round((first.value / upper) * 100))
  assert.ok(spec.refLines?.some((line) => line.y === 100), '100% is the reference limit')
})

test('a spectrum stays in frequency order rather than sorting by amplitude', () => {
  // The diagnosis is which harmonic is elevated (1X = imbalance, BPFO = outer
  // race). Sorting by amplitude destroys exactly the information being read.
  const spec = chartFor('analyze_vibration', payloads.analyze_vibration)!
  const peaks = (
    payloads.analyze_vibration as {
      frequency_peaks: Array<{ label: string; frequency_hz: number }>
    }
  ).frequency_peaks
  const hz = new Map(peaks.map((p) => [p.label, p.frequency_hz]))
  const charted = spec.data.map((row) => hz.get(String(row.peak))!)
  assert.deepEqual(charted, [...charted].sort((a, b) => a - b))
  const amps = spec.data.map((row) => Number(row.amp))
  assert.notDeepEqual(
    amps,
    [...amps].sort((a, b) => b - a),
    'the fixture no longer distinguishes frequency order from amplitude order',
  )
})

test('a calendar and a schedule stay chronological', () => {
  // Ranking a date axis by value makes "when is the next opening" unanswerable.
  const avail = chartFor('get_provider_availability', payloads.get_provider_availability)!
  const dates = (
    payloads.get_provider_availability as { availability: Array<{ date: string }> }
  ).availability.map((a) => a.date)
  assert.deepEqual(
    avail.data.map((row) => row.day),
    dates,
  )
  const slots = avail.data.map((row) => Number(row.slots))
  assert.notDeepEqual(
    slots,
    [...slots].sort((a, b) => b - a),
    'the fixture no longer distinguishes date order from slot-count order',
  )
})

test('a single score is charted against the benchmarks the payload carries', () => {
  // One bar is not a chart, and a risk score alone answers nothing — 8.9% is
  // only meaningful beside the 15.6% national average it beats.
  const spec = chartFor('get_readmission_risk', payloads.get_readmission_risk)!
  const raw = payloads.get_readmission_risk as {
    risk_score: number
    benchmark: { national_avg_readmission_rate: string; cms_penalty_threshold: string }
  }
  assert.ok(spec.data.length >= 3, 'patient plus both benchmarks')
  assert.equal(spec.data[0].rate, raw.risk_score)
  assert.equal(
    spec.data[1].rate,
    Number.parseFloat(raw.benchmark.national_avg_readmission_rate),
  )
  // A lone score with no benchmarks must not become a one-bar chart.
  assert.equal(
    chartFor('get_readmission_risk', {
      risk_score: 8.9,
      social_determinants: { lives_alone: false },
      benchmark: {},
    }),
    null,
  )
})

test('care gaps are ranked by days past due, computed from the due date', () => {
  // "HIGH" and "OVERDUE" are not orderable; days past due is, which is the whole
  // reason this recognizer computes rather than reads.
  const spec = chartFor('get_care_gap_analysis', payloads.get_care_gap_analysis)!
  const gaps = (
    payloads.get_care_gap_analysis as {
      care_gaps: Array<{ measure: string; due_date: string }>
    }
  ).care_gaps
  // One real gap has due_date "Next flu season (Oct)" — a phrase, not a date. It
  // must be dropped: parsed as 0 it would plot as "due today" and rank above
  // every genuinely overdue measure.
  const prose = gaps.filter((g) => !Number.isFinite(Date.parse(g.due_date)))
  assert.equal(prose.length, 1, 'fixture no longer exercises the unparseable-date path')
  assert.equal(spec.data.length, gaps.length - prose.length)
  assert.ok(!spec.data.some((row) => row.measure === prose[0].measure))
  const overdue = spec.data.map((row) => Number(row.overdue))
  assert.deepEqual(overdue, [...overdue].sort((a, b) => b - a))
  // Sanity-check the arithmetic against one row rather than trusting the sort.
  const worst = spec.data[0]
  const gap = gaps.find((g) => g.measure === worst.measure)!
  const expected = Math.round((Date.now() - Date.parse(gap.due_date)) / 86_400_000)
  assert.equal(worst.overdue, expected)
})

/*
 * Mutation results (each applied to web/src/lib/chartSpec.ts, run, reverted).
 * Round 1 covered the original 18 recognizers:
 *
 *  1. `project` accepts length >= 1 instead of >= 2   → 1 failure (single-row)
 *  2. `num()` returns 0 rather than undefined         → 1 failure (non-numeric
 *     dropped, not zeroed)
 *  3. sector chart no longer sorts                    → 1 failure
 *  4. sensor thresholds emitted as a series           → 2 failures
 *  5. `num()` drops its parseFloat string branch      → 3 failures
 *  6. `chartFor` returns a stub spec for unknown tools → 1 failure
 *  7. sector recognizer reads `ytd_change_pct` as `daily` → 1 failure
 *     (charted-values-match-payload — the one that catches a silent mis-mapping)
 *  8. equipment health chart no longer sorts          → 1 failure
 *
 * Round 2 targeted the 25 recognizers added for the uncovered starter questions.
 * Each mutation is a plausible-looking chart that would misinform the reader, and
 * all 11 were killed (2 failures each — the specific assertion plus one of the
 * cross-cutting loops). Script: /tmp/mutate.py.
 *
 *  9. vibration spectrum sorted by amplitude instead of frequency
 * 10. provider availability ranked by slot count instead of chronological
 * 11. weekly capacity reference line drawn as the whole-period total
 * 12. supplier scorecard keeps defect_rate_ppm alongside the 0-100 metrics
 * 13. lab values plotted raw instead of as a percentage of their upper limit
 * 14. `daysPast` returns 0 for an unparseable date ("Next flu season (Oct)"),
 *     making a gap with no real due date rank as due today
 * 15. readmission score charted alone, with the benchmark guard removed
 * 16. listing prices lose the market-median reference line
 * 17. per-type medians lose the all-types median reference line
 * 18. `check_drug_interactions` dropped from the registry (stands in for any
 *     recognizer being lost — the per-question coverage test catches it)
 * 19. care gaps no longer ranked by days overdue
 * 20. the empty-interactions guard removed, so an all-zero severity summary
 *     draws three zero-height bars
 *
 * Mutants 16 and 17 edit textually identical lines in two different recognizers,
 * so each is anchored on its own preceding comment. Anchoring on the shared text
 * alone mutated only the first and reported a false survivor — which is how the
 * missing assertion for #17 was found.
 *
 * One mutant SURVIVES, and it is worth naming rather than hiding: deleting the
 * `'error' in payload` guard in `chartFor` changes nothing measurable, because a
 * `{"error": "..."}` body also fails every recognizer's shape check and exits by
 * the next return. The guard is documentation of an intended case, not load-
 * bearing behaviour. It stays because tool_error() payloads arrive as *successful*
 * tool results, which is surprising enough to state at the boundary, but no test
 * here can distinguish it — and a test written to pin it would be pinning the
 * implementation rather than the behaviour.
 */
