/**
 * The chart recognizers, run against real tool payloads.
 *
 *   node --test tests/unit/chartSpec.test.ts
 *
 * `tests/fixtures/tool_payloads.json` is not hand-written: it is the actual
 * output of 18 gateway tool functions, generated by importing the Lambda handlers
 * and calling them. That matters because the recognizers index into specific key
 * names (`weekly_data[].units_sold`, `trends[].median_sale_price`), and a test
 * built on invented payloads would pass while the real shapes drifted underneath.
 *
 * The assertions that carry the most weight are the negative ones. This feature
 * shows a chart next to an agent's answer, so a *wrong* chart is worse than no
 * chart — the numbers on screen would contradict the numbers in the reply. So
 * every recognizer must return null rather than half-draw when the payload does
 * not match, and unrecognized tools must produce nothing at all.
 *
 * Mutation-checked; see the bottom of this file for what was verified.
 */
import { test } from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { chartFor, CHARTABLE_TOOLS } from '../../web/src/lib/chartSpec.ts'

const payloads = JSON.parse(
  readFileSync(new URL('../fixtures/tool_payloads.json', import.meta.url), 'utf8'),
) as Record<string, unknown>

/** Guard against a vacuous suite: an empty fixture would satisfy every loop. */
test('the fixture holds real payloads for every chartable tool', () => {
  assert.ok(
    Object.keys(payloads).length >= 18,
    `fixture has ${Object.keys(payloads).length} payloads; expected the full capture`,
  )
  for (const tool of CHARTABLE_TOOLS) {
    assert.ok(payloads[tool], `no captured payload for ${tool} — its test would be vacuous`)
  }
})

test('every chartable tool produces a chart from its real payload', () => {
  for (const tool of CHARTABLE_TOOLS) {
    const spec = chartFor(tool, payloads[tool])
    assert.ok(spec, `${tool}: recognizer returned null for its own real payload`)
    assert.ok(spec.title.trim(), `${tool}: empty title`)
    assert.ok(spec.data.length >= 2, `${tool}: ${spec.data.length} rows — not a chart`)
    assert.ok(spec.series.length >= 1, `${tool}: no series`)
  }
})

test('every series key resolves to a finite number in every row', () => {
  // The failure this prevents is a chart that renders as a flat line or an empty
  // grid: recharts silently draws nothing for a key that is missing or a string,
  // so a typo'd key produces an axis with no data rather than an error.
  for (const tool of CHARTABLE_TOOLS) {
    const spec = chartFor(tool, payloads[tool])!
    for (const series of spec.series) {
      for (const [i, row] of spec.data.entries()) {
        const value = row[series.key]
        assert.equal(
          typeof value,
          'number',
          `${tool}: row ${i} key "${series.key}" is ${typeof value}, not a number`,
        )
        assert.ok(
          Number.isFinite(value as number),
          `${tool}: row ${i} key "${series.key}" is not finite`,
        )
      }
    }
    for (const [i, row] of spec.data.entries()) {
      const x = row[spec.xKey]
      assert.ok(
        typeof x === 'string' || typeof x === 'number',
        `${tool}: row ${i} has no x value at "${spec.xKey}"`,
      )
    }
  }
})

test('charted values match the payload rather than being recomputed', () => {
  // Spot-check the two shapes with the most transformation between payload and
  // chart. If a recognizer ever starts deriving values, the panel would show
  // numbers the agent's reply does not contain — the exact defect this whole
  // feature exists to avoid.
  const sectors = chartFor('get_sector_performance', payloads.get_sector_performance)!
  const raw = (payloads.get_sector_performance as { sectors: Array<Record<string, unknown>> })
    .sectors
  const tech = raw.find((s) => s.name === 'Technology')!
  const charted = sectors.data.find((row) => row.sector === 'Technology')!
  assert.equal(charted.daily, tech.daily_change_pct)

  const bp = chartFor('get_patient_analytics', payloads.get_patient_analytics)!
  const bpRaw = (
    payloads.get_patient_analytics as {
      trends: { blood_pressure: { data: Array<Record<string, unknown>> } }
    }
  ).trends.blood_pressure.data
  assert.equal(bp.data.length, bpRaw.length)
  assert.equal(bp.data[0].systolic, bpRaw[0].systolic)
  assert.equal(bp.data[0].diastolic, bpRaw[0].diastolic)
})

test('ranked charts are sorted so the extremes read off the ends', () => {
  // "Which sectors are leading and lagging" is a literal starter question; an
  // unsorted bar chart answers it worse than the table did.
  const sectors = chartFor('get_sector_performance', payloads.get_sector_performance)!
  const values = sectors.data.map((row) => Number(row.daily))
  assert.deepEqual(values, [...values].sort((a, b) => b - a))

  // Health scores sort the other way: the asset needing attention goes first.
  const fleet = chartFor('get_equipment_list', payloads.get_equipment_list)!
  const health = fleet.data.map((row) => Number(row.health))
  assert.deepEqual(health, [...health].sort((a, b) => a - b))
})

test('an unrecognized tool produces no chart', () => {
  // The panel must stay hidden for the many tools with nothing to plot, rather
  // than inventing an axis out of whatever numbers a payload happens to hold.
  for (const tool of ['skills', 'search_knowledge_base', 'place_order', 'schedule_appointment']) {
    assert.equal(chartFor(tool, { anything: [1, 2, 3] }), null, `${tool} should not chart`)
  }
})

test('a recognized tool with the wrong payload shape produces no chart', () => {
  // Tool output changing shape must degrade to "no panel", never to a broken axis.
  for (const tool of CHARTABLE_TOOLS) {
    for (const junk of [null, undefined, {}, [], 'text', 42, { sectors: [] }, { data: {} }]) {
      assert.equal(
        chartFor(tool, junk),
        null,
        `${tool}: charted junk payload ${JSON.stringify(junk)}`,
      )
    }
  }
})

test('a tool error payload produces no chart', () => {
  // tool_error() returns {"error": "..."} with HTTP success, so this arrives as a
  // successful tool result and would otherwise reach the recognizers.
  assert.equal(
    chartFor('get_sector_performance', { error: 'Portfolio not found: default' }),
    null,
  )
  assert.equal(chartFor('get_market_overview', { error: 'boom', indices: {} }), null)
})

test('a single-row payload produces no chart', () => {
  // One bar is a number with extra ink. The threshold is where the panel stops
  // being an improvement over the sentence in the reply.
  assert.equal(
    chartFor('get_demand_trends', { weekly_data: [{ week: '2026-W28', units_sold: 100 }] }),
    null,
  )
})

test('non-numeric values are dropped rather than coerced to zero', () => {
  // A null reading plotted as 0 would put a spike to the baseline on a vibration
  // chart, which reads as an equipment fault that did not happen.
  const spec = chartFor('get_sensor_data', {
    sensor_type: 'vibration',
    equipment_id: 'EQ-CNC-001',
    unit: 'mm/s',
    readings: [
      { timestamp: '2026-08-05T01:00:00Z', value: 3.1 },
      { timestamp: '2026-08-05T02:00:00Z', value: null },
      { timestamp: '2026-08-05T03:00:00Z', value: 3.4 },
    ],
    thresholds: { warning: 5, critical: 8 },
  })!
  assert.equal(spec.data.length, 2, 'the null reading should be dropped, not zeroed')
  assert.deepEqual(
    spec.data.map((row) => row.value),
    [3.1, 3.4],
  )
})

test('sensor thresholds become dashed reference lines, not series', () => {
  // Status thresholds as a data series would read as a measurement.
  const spec = chartFor('get_sensor_data', payloads.get_sensor_data)!
  assert.equal(spec.series.length, 1)
  assert.ok(spec.refLines && spec.refLines.length >= 1, 'thresholds should be reference lines')
  const thresholds = (payloads.get_sensor_data as { thresholds: Record<string, number> })
    .thresholds
  assert.ok(spec.refLines!.some((line) => line.y === thresholds.critical))
})

test('percentage strings in HEDIS measures are parsed, not dropped', () => {
  // These arrive as "81%", the one place a payload reports a number as a string.
  const spec = chartFor('get_population_health_metrics', payloads.get_population_health_metrics)!
  const measures = (
    payloads.get_population_health_metrics as {
      quality_measures_hedis: Record<string, { performance: string }>
    }
  ).quality_measures_hedis
  assert.equal(spec.data.length, Object.keys(measures).length)
  const first = Object.values(measures)[0]
  assert.equal(spec.data[0].performance, Number.parseFloat(first.performance))
})

/*
 * Mutation results (each applied to web/src/lib/chartSpec.ts, run, reverted):
 *
 *  1. `project` accepts length >= 1 instead of >= 2   → 1 failure (single-row)
 *  2. `num()` returns 0 rather than undefined         → 1 failure (non-numeric
 *     dropped, not zeroed)
 *  3. sector chart no longer sorts                    → 1 failure
 *  4. sensor thresholds emitted as a series           → 2 failures
 *  5. `num()` drops its parseFloat string branch      → 3 failures
 *  6. `chartFor` returns a stub spec for unknown tools → 1 failure
 *  7. sector recognizer reads `ytd_change_pct` as `daily` → 1 failure
 *     (charted-values-match-payload — the one that catches a silent mis-mapping)
 *  8. equipment health chart no longer sorts          → 1 failure
 *
 * One mutant SURVIVES, and it is worth naming rather than hiding: deleting the
 * `'error' in payload` guard in `chartFor` changes nothing measurable, because a
 * `{"error": "..."}` body also fails every recognizer's shape check and exits by
 * the next return. The guard is documentation of an intended case, not load-
 * bearing behaviour. It stays because tool_error() payloads arrive as *successful*
 * tool results, which is surprising enough to state at the boundary, but no test
 * here can distinguish it — and a test written to pin it would be pinning the
 * implementation rather than the behaviour.
 */
